server:
  # 服务端口
  port: 8082
  servlet:
    # 项目contextPath
    context-path: /admin
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

spring:
  application:
    name: admin-server
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      initialSize: 6
      master:
        url: jdbc:mysql://139.196.72.210:3306/web_example_vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: 123456
      slave:
        enabled: false
        url: jdbc:mysql://139.196.72.210:3306/web_example_vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: 123456
      statViewServlet:
        enabled: true
        url-pattern: /monitor/druid/*
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  redis:
    database: 0
    host: 139.196.72.210
    port: 6379
    password: 123456
  session:
    store-type: redis
# mybatis配置
mybatis:
  # 加载全局的配置文件
  config-location: classpath:config/mybatis-config.xml
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath*:mapper/**/*Mapper.xml

# dubbo服务
dubbo:
  registry:
    address: zookeeper://139.196.72.210:2181
  application:
    name: admin-web

# 项目配置
project:
  web:
    filter:
      # 允许匿名访问的地址
      anon-urls:
        - /static/**
        - /system/dictOption/queryEnableUse
        - /core/common/queryCode
      login-url: /sso/admin/login